/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controllers.OvertimeController;
import controllers.OvertimeControllerInterface;
import controllers.PresenceController;
import controllers.PresenceControllerInterface;
import entities.Overtime;
import entities.Presence;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.hibernate.SessionFactory;
import tools.HibernateUtil;

/**
 *
 * @author tikamhrdk
 */
public class ManagerOvertimeReq extends javax.swing.JInternalFrame {
    
    private SessionFactory sessionFactory;
    private OvertimeControllerInterface oci;
    

    
//    void cleanField() {
//        txtSearch.setText("");
//        txtLocationId.setText("");
//        txtPostalCode.setText("");
//        txtCity.setText("");
//        txtStateProvince.setText("");
//        txtStreetAdrress.setText("");
//        comboCountry.setSelectedItem("Select Country");
//    }

    public void Binding(List<Object> overtimes) {
        Object[] header = {"No", "Overtime_Id", "Name", "NIK", "Duration", "Fee", "Status", "Timesheet"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        overtimeTabel.setModel(data);
        int number = 1;

        try {
            for (Object overtime : overtimes) {
                Overtime o = (Overtime) overtime;
                String Number = String.valueOf(number);
                String isi1 = String.valueOf(o.getOvertimeId());
                String isi2 = String.valueOf(o.getNik().getName());
                String isi3 = String.valueOf(o.getNik());
                String isi4 = String.valueOf(o.getOtDuration());
                String isi5 = String.valueOf(o.getFee());
                String isi6 = String.valueOf(o.getStatus());
                String isi7 = String.valueOf(o.getTsFile());

                String kolom[] = {Number, isi1, isi2, isi3, isi4, isi5, isi6, isi7};
                number++;
                data.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ckck" + e.getMessage());
        }
    }

    /**
     * Creates new form ManagerOvertimeReq
     */
    public ManagerOvertimeReq() {
        sessionFactory = HibernateUtil.getSessionFactory();
        oci = new OvertimeController(sessionFactory);
        initComponents();
        
        
//        cleanField();
        
        Binding(oci.getAlls());

        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        overtimeTabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        overtimeField = new javax.swing.JTextField();
        nikField = new javax.swing.JTextField();
        presenceField = new javax.swing.JTextField();
        durationField = new javax.swing.JTextField();
        feeField = new javax.swing.JTextField();
        statusappcmb = new javax.swing.JComboBox<>();
        savebtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        overtimeTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "Title 6", "Title 7", "Title 8"
            }
        ));
        overtimeTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overtimeTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(overtimeTabel);

        jLabel1.setText("Overtime_Id");

        jLabel2.setText("NIK");

        jLabel3.setText("Presence_Id");

        jLabel4.setText("Duration");

        jLabel5.setText("Fee");

        jLabel6.setText("Status");

        nikField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikFieldActionPerformed(evt);
            }
        });

        presenceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presenceFieldActionPerformed(evt);
            }
        });

        durationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationFieldActionPerformed(evt);
            }
        });

        statusappcmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Approve", "Reject", " " }));

        savebtn.setText("save");

        jMenu1.setText("Reports");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Overtime Req.");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Logout");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(savebtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(39, 39, 39)
                            .addComponent(statusappcmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(52, 52, 52)
                            .addComponent(feeField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(29, 29, 29)
                            .addComponent(durationField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(53, 53, 53)
                            .addComponent(nikField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(overtimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(presenceField))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(overtimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nikField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(presenceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(feeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(statusappcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(savebtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nikFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nikFieldActionPerformed

    private void presenceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presenceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presenceFieldActionPerformed

    private void durationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationFieldActionPerformed

    private void overtimeTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overtimeTabelMouseClicked
        int i = overtimeTabel.getSelectedRow();
        TableModel model = overtimeTabel.getModel();        
        overtimeField.setText(model.getValueAt(i, 1).toString());
        nikField.setText(model.getValueAt(i, 4).toString());
        Overtime overtime = (Overtime) oci.getById((String) model.getValueAt(i, 1));
        String present = String.valueOf(overtime.getPresenceId());
        presenceField.setText(present);
        durationField.setText(model.getValueAt(i, 5).toString());
        feeField.setText(model.getValueAt(i, 6).toString());
                                            

//    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {                                       
//        if (lc.deleteLocation(txtLocationId.toString(), txtCity.toString())){
//            JOptionPane.showMessageDialog(null, "Sukses delete");
//        }
//        else{
//            JOptionPane.showMessageDialog(null, "gagal delete");
//        }
    }//GEN-LAST:event_overtimeTabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField durationField;
    private javax.swing.JTextField feeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nikField;
    private javax.swing.JTextField overtimeField;
    private javax.swing.JTable overtimeTabel;
    private javax.swing.JTextField presenceField;
    private javax.swing.JButton savebtn;
    private javax.swing.JComboBox<String> statusappcmb;
    // End of variables declaration//GEN-END:variables
}
