/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.EmployeeController;
import controllers.EmployeeControllerInterface;
import controllers.OvertimeController;
import controllers.OvertimeControllerInterface;
import controllers.PresenceController;
import controllers.PresenceControllerInterface;
import entities.Overtime;
import entities.Presence;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import org.hibernate.SessionFactory;
import tools.Datas;
import tools.HibernateUtil;
import javax.swing.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

class mycustomFilter extends javax.swing.filechooser.FileFilter {

    @Override
    public boolean accept(File file) {
        return file.isDirectory() || file.getAbsolutePath().endsWith(".pdf");
    }

    @Override
    public String getDescription() {
        return "File pdf (*.pdf)";
    }

}

/**
 *
 * @author Mukhlish
 */
public class mainFormEmployee extends javax.swing.JFrame {

    SessionFactory factory = HibernateUtil.getSessionFactory();
    PresenceControllerInterface pci = new PresenceController(factory);
    EmployeeControllerInterface eci = new EmployeeController(factory);
    OvertimeControllerInterface oci = new OvertimeController(factory);
    JFileChooser jfc;

    /**
     * Creates new form mainFormEmployee
     */
    public mainFormEmployee() {
        initComponents();

        txtNIK1.setText(Datas.getNik());
        txtName1.setText(Datas.getName());
        txtEmail1.setText(Datas.getemail());
        txtPhone1.setText(Datas.getNotelp());
        txtDate1.setText(Datas.getHire_date());
        txtJob1.setText(Datas.geteJob_title());
//        txt.setText(Datas.getSalary());
        txtStatus1.setText(Datas.getStatus());
        txtManager1.setText(Datas.getManager_id());
        txtNIK1.setEditable(false);
        txtName1.setEditable(false);
        txtEmail1.setEditable(false);
        txtManager1.setEditable(false);
        txtPhone1.setEditable(false);
        txtManager1.setEditable(false);
        txtStatus1.setEditable(false);
        txtDate1.setEditable(false);
        txtJob1.setEditable(false);
        txtPass1.setEditable(false);

        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        BindingOvertime(oci.search(txtSearch.getText()));

        DashboardEmp.setVisible(true);
        OTreq.setVisible(false);

    }

    public void BindingOvertime(List<Object> overtimes) {
        Object[] header = {"No", "Overtime_Id", "Name", "NIK", "Duration", "Fee", "Status", "Timesheet"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        tblOvertime.setModel(data);
        int number = 1;

        try {
            for (Object overtime : overtimes) {
                Overtime o = (Overtime) overtime;
                String Number = String.valueOf(number);
                String Isi1 = String.valueOf(o.getOvertimeId());
                String Isi2 = String.valueOf(o.getNik().getName());
                String Isi3 = String.valueOf(o.getNik().getNik());
                String Isi4 = String.valueOf(o.getOtDuration());
                String Isi5 = String.valueOf(o.getFee());
                String status = String.valueOf(o.getStatus());
                if (status.matches("0")) {
                    status = "request";
                } else if (status.matches("1")) {
                    status = "Approved";
                } else if (status.matches("2")) {
                    status = "rejected";
                }
                String Isi6 = status;
                String Isi7 = String.valueOf(o.getTsFile());

                String kolom[] = {Number, Isi1, Isi2, Isi3, Isi4, Isi5, Isi6, Isi7};
                number++;
                data.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ckck" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashboardEmp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCheckIn = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtNIK1 = new javax.swing.JTextField();
        txtName1 = new javax.swing.JTextField();
        txtEmail1 = new javax.swing.JTextField();
        txtPhone1 = new javax.swing.JTextField();
        txtDate1 = new javax.swing.JTextField();
        txtJob1 = new javax.swing.JTextField();
        txtStatus1 = new javax.swing.JTextField();
        txtManager1 = new javax.swing.JTextField();
        btnEditProfile = new javax.swing.JToggleButton();
        txtPass1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        OTreq = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOvertime = new javax.swing.JTable();
        btnBrows = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        txtDir = new javax.swing.JTextField();
        btnUpload = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        DasboardEmp = new javax.swing.JMenu();
        OTReq = new javax.swing.JMenu();
        LogoutEmp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("NIK                         :");

        jLabel2.setText("Name                      :");

        jLabel3.setText("Email                       :");

        jLabel4.setText("Phone Number      :");

        jLabel5.setText("Hire date                : ");

        jLabel6.setText("Job Title                 : ");

        jLabel7.setText("Status                    :");

        jLabel8.setText("Manger                   :");

        btnCheckIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCheckIn.setText("Check In");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        txtNIK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIK1ActionPerformed(evt);
            }
        });

        btnEditProfile.setText("Edit Profile");
        btnEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProfileActionPerformed(evt);
            }
        });

        txtPass1.setText("jPasswordField1");

        jLabel9.setText("Change password");

        jLabel12.setText("Password               :     ");

        javax.swing.GroupLayout DashboardEmpLayout = new javax.swing.GroupLayout(DashboardEmp);
        DashboardEmp.setLayout(DashboardEmpLayout);
        DashboardEmpLayout.setHorizontalGroup(
            DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardEmpLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNIK1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtName1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPhone1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDate1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtJob1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtStatus1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPass1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(txtManager1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnEditProfile)
                        .addComponent(txtEmail1))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        DashboardEmpLayout.setVerticalGroup(
            DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(DashboardEmpLayout.createSequentialGroup()
                .addGroup(DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DashboardEmpLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(DashboardEmpLayout.createSequentialGroup()
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addComponent(txtNIK1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(7, 7, 7)
                        .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtJob1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtManager1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnEditProfile)))
                .addContainerGap())
            .addGroup(DashboardEmpLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblOvertime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOvertime);

        btnBrows.setText("Browse");
        btnBrows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBrowsMouseClicked(evt);
            }
        });

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        txtDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirActionPerformed(evt);
            }
        });

        btnUpload.setText("Upload");
        btnUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUploadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUploadMouseEntered(evt);
            }
        });

        jLabel10.setText("Browse File ");

        jLabel11.setText("Search by Date");

        javax.swing.GroupLayout OTreqLayout = new javax.swing.GroupLayout(OTreq);
        OTreq.setLayout(OTreqLayout);
        OTreqLayout.setHorizontalGroup(
            OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OTreqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(OTreqLayout.createSequentialGroup()
                        .addGroup(OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OTreqLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(32, 32, 32)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(OTreqLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(33, 33, 33)
                                .addGroup(OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpload)
                                    .addGroup(OTreqLayout.createSequentialGroup()
                                        .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBrows)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        OTreqLayout.setVerticalGroup(
            OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OTreqLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrows))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpload)
                .addGap(5, 5, 5))
        );

        DasboardEmp.setText("Dashboard");
        DasboardEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DasboardEmpMouseClicked(evt);
            }
        });
        DasboardEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DasboardEmpActionPerformed(evt);
            }
        });
        jMenuBar1.add(DasboardEmp);

        OTReq.setText("Overtime");
        OTReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OTReqMouseClicked(evt);
            }
        });
        jMenuBar1.add(OTReq);

        LogoutEmp.setText("Log out");
        LogoutEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutEmpMouseClicked(evt);
            }
        });
        jMenuBar1.add(LogoutEmp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(DashboardEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OTreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(DashboardEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(41, Short.MAX_VALUE)
                    .addComponent(OTreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DasboardEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DasboardEmpActionPerformed

    }//GEN-LAST:event_DasboardEmpActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        String NIK = Datas.getNik();
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        String dates = String.valueOf(timestamp);
        String hasil = "";
        String b = dates.substring(0, 10);
        String[] c = b.split("-");
        for (int i = 0; i < c.length; i++) {
            hasil = c[1] + "/" + c[2] + "/" + c[0];
        }
        String time = String.valueOf(timestamp);
        String times = time.substring(11, 19);
        int autiID = pci.getAlls().size() + 104;
        String ID = String.valueOf(autiID);
        System.out.println(ID);
        Datas.setIdPresence(ID);
        if (btnCheckIn.isSelected()) {

            System.out.println(ID + NIK + times + null + dates);
            if (pci.insert(ID, NIK, times, null, hasil)) {
                JOptionPane.showMessageDialog(null, "Check In succes");
            } else {
                JOptionPane.showMessageDialog(null, "Check In Failled!");
            }
            btnCheckIn.setText("Check Out");
        } else {

            OvertimeForm overtimeForm = new OvertimeForm();
            overtimeForm.show();
            int Id = autiID - 1;
            String IDnew = String.valueOf(Id);
            Presence pi = pci.getById(IDnew);
            String cekin = pi.getCheckIn();
            System.out.println(IDnew);

            if (pci.update(IDnew, NIK, cekin, times, hasil)) {
//                JOptionPane.showMessageDialog(null, "Check Out succes");
            } else {
                JOptionPane.showMessageDialog(null, "Check Out Failled!");
            }
            btnCheckIn.setText("Check In");
            btnCheckIn.setEnabled(false);
        }
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void DasboardEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DasboardEmpMouseClicked
        DashboardEmp.setVisible(true);
        OTreq.setVisible(false);
    }//GEN-LAST:event_DasboardEmpMouseClicked

    private void OTReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OTReqMouseClicked
        DashboardEmp.setVisible(false);
        OTreq.setVisible(true);
        BindingOvertime(oci.search(txtSearch.getText()));

    }//GEN-LAST:event_OTReqMouseClicked

    private void txtNIK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIK1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIK1ActionPerformed

    private void LogoutEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutEmpMouseClicked
        int dialogButton = 0;
        int dialog = JOptionPane.showConfirmDialog(null, "Apakah anda ingin Logout ?", "Warning", dialogButton);
        if (dialog == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            LoginForm loginForm = new LoginForm();
            loginForm.show();
        } else {
        }
    }//GEN-LAST:event_LogoutEmpMouseClicked

    private void btnBrowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowsMouseClicked
//        FileChooser jfc = new FileChooser();
//       
//       jfc.showOpenDialog(null);
//
//        File file = jfc.getInitialDirectory();
//        String dir = file.getAbsolutePath();
//
//        txtDir.setText(dir);

        if (jfc == null) {
            jfc = new JFileChooser();
            jfc.addChoosableFileFilter(new mycustomFilter());
            jfc.setAcceptAllFileFilterUsed(false);

        }

        int returnfVal = jfc.showOpenDialog(mainFormEmployee.this);
        if (returnfVal == JFileChooser.APPROVE_OPTION) {
            File file = jfc.getSelectedFile();
            String dir = file.getAbsolutePath();
            txtDir.setText(dir);
        }
    }//GEN-LAST:event_btnBrowsMouseClicked

    private void txtDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        BindingOvertime(oci.search(txtSearch.getText()));
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProfileActionPerformed
                if (btnEditProfile.isSelected()) {
            txtNIK1.setEditable(false);
            txtName1.setEditable(false);
            txtEmail1.setEditable(true);
            txtManager1.setEditable(false);
            txtPhone1.setEditable(true);
            txtStatus1.setEditable(false);
            txtDate1.setEditable(false);
            txtJob1.setEditable(false);
            txtPass1.setEditable(false);

            btnEditProfile.setText("Save");
        } else {
            String NIK = Datas.getNik();
            String Name = Datas.getName();
            String email = txtEmail1.getText();
            String Password = Datas.getPassword();
            String Phone = txtPhone1.getText();
            String hireDate = txtDate1.getText();
            String Job = Datas.geteJob_title();
            String Status = Datas.getStatus();
            String Manager = Datas.getManager_id();
            String Salary = Datas.getSalary();
            String isDel = Datas.getIsDelete();


            if (!email.equals("") && !Phone.equals("")) {
                if (eci.update(Name, email, Password, Phone, hireDate, Job, Salary, Manager, Status, isDel, NIK)) {
                    JOptionPane.showMessageDialog(null, "insert berhasil");

                } else {
                    JOptionPane.showMessageDialog(null, "insert gagal");
                }

            } else {
                JOptionPane.showMessageDialog(null, "form input tidak boleh kosong");
            }
            txtNIK1.setEditable(false);
            txtName1.setEditable(false);
            txtEmail1.setEditable(false);
            txtManager1.setEditable(false);
            txtPhone1.setEditable(false);
            txtManager1.setEditable(false);
            txtStatus1.setEditable(false);
            txtDate1.setEditable(false);
            txtJob1.setEditable(false);
            txtPass1.setEditable(false);
            btnEditProfile.setText("Edit Profile");
        }
    }//GEN-LAST:event_btnEditProfileActionPerformed

    private void btnUploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUploadMouseClicked

        int i = tblOvertime.getSelectedRow();
        TableModel model = tblOvertime.getModel();
        String ID = (String) model.getValueAt(i, 1);
        String NIK = model.getValueAt(i, 3).toString();
        Overtime overtime = (Overtime) oci.getById((String) model.getValueAt(i, 1));
        String IDpresence = String.valueOf(overtime.getPresenceId().getPresenceId());

        String path = txtDir.getText();
        String Duration = model.getValueAt(i, 4).toString();

        String Fee = model.getValueAt(i, 5).toString();
        String Status = model.getValueAt(i, 6).toString();
        
        if (Status.matches("request")) {
            Status = "0";
        } else if (Status.matches("Approved")) {
            Status = "1";
        } else if (Status.matches("rejected")) {
            Status = "2";
        }

        if (oci.update(ID, NIK, IDpresence, Duration, Fee, Status, path)) {
            JOptionPane.showMessageDialog(null, "Succes");
            txtDir.setText("");
            BindingOvertime(oci.search(txtSearch.getText()));
            //JOptionPane.showMessageDialog(null, "Check Out succes");
            //employeeid_field.setText(employeeController.lastId());
        } else {
            JOptionPane.showMessageDialog(null, "Failed");
        }
    }//GEN-LAST:event_btnUploadMouseClicked

    private void btnUploadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUploadMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFormEmployee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFormEmployee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFormEmployee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFormEmployee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFormEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DasboardEmp;
    private javax.swing.JPanel DashboardEmp;
    private javax.swing.JMenu LogoutEmp;
    private javax.swing.JMenu OTReq;
    private javax.swing.JPanel OTreq;
    private javax.swing.JButton btnBrows;
    private javax.swing.JToggleButton btnCheckIn;
    private javax.swing.JToggleButton btnEditProfile;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblOvertime;
    private javax.swing.JTextField txtDate1;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtJob1;
    private javax.swing.JTextField txtManager1;
    private javax.swing.JTextField txtNIK1;
    private javax.swing.JTextField txtName1;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStatus1;
    // End of variables declaration//GEN-END:variables
}
