/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.EmployeeController;
import controllers.EmployeeControllerInterface;
import controllers.OvertimeController;
import controllers.OvertimeControllerInterface;
import controllers.PresenceController;
import controllers.PresenceControllerInterface;
import entities.Overtime;
import entities.Presence;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Timestamp;
import javafx.stage.FileChooser;
import javax.mail.Session;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import org.hibernate.SessionFactory;
import tools.Datas;
import tools.HibernateUtil;
import javax.swing.*;
import java.io.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;

class mycustomFilter extends javax.swing.filechooser.FileFilter {
    public boolean accept(File file){
        return file.isDirectory() || file.getAbsolutePath().endsWith(".pdf");
    }
    public String getDescription(){
        return "File pdf (*.pdf)";
    }
    
}

/**
 *
 * @author Mukhlish
 */
public class mainFormEmployee extends javax.swing.JFrame {

    SessionFactory factory = HibernateUtil.getSessionFactory();
    PresenceControllerInterface pci = new PresenceController(factory);
    EmployeeControllerInterface eci = new EmployeeController(factory);
    OvertimeControllerInterface oci = new OvertimeController(factory);
    JFileChooser jfc;
    

    /**
     * Creates new form mainFormEmployee
     */
    public mainFormEmployee() {
        initComponents();

        txtNIK.setText(Datas.getNik());
        txtName.setText(Datas.getName());
        txtEmail.setText(Datas.getemail());
        txtPhone.setText(Datas.getNotelp());
//        txt.setText(Datas.getSalary());
        txtNIK1.setText(Datas.getNik());
        txtName1.setText(Datas.getName());
        txtEmail1.setText(Datas.getemail());
        txtPhone1.setText(Datas.getNotelp());
        txtDate1.setText(Datas.getHire_date());
        txtJob1.setText(Datas.geteJob_title());
//        txt.setText(Datas.getSalary());
        txtStatus1.setText(Datas.getStatus());
        txtManager1.setText(Datas.getManager_id());

        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
//        BindingOvertime(oci.search(txtSearch.getText()));

        DashboardEmp.setVisible(true);
        ProfilEmp.setVisible(false);
        OTreq.setVisible(false);
        
        txtDisable1();
        txtNIK.setEnabled(false);
    }
    
    public void txtDisable1(){
        txtNIK1.setEditable(false);
        txtName1.setEditable(false);
        txtEmail1.setEditable(false);
        txtPhone1.setEditable(false);
        txtDate1.setEditable(false);
        txtJob1.setEditable(false);
        txtStatus1.setEditable(false);
        txtManager1.setEditable(false);
    }
     public void BindingOvertime(List<Object> overtimes) {
        Object[] header = {"No", "Overtime_Id", "Name", "NIK", "Duration", "Fee", "Status", "Timesheet"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        tblOvertime.setModel(data);
        int number = 1;

        try {
            for (Object overtime : overtimes) {
                Overtime o = (Overtime) overtime;
                String Number = String.valueOf(number);
                String Isi1 = String.valueOf(o.getOvertimeId());
                String Isi2 = String.valueOf(o.getNik().getName());
                String Isi3 = String.valueOf(o.getNik().getNik());
                String Isi4 = String.valueOf(o.getOtDuration());
                String Isi5 = String.valueOf(o.getFee());
                String status = String.valueOf(o.getStatus());
                if (status.matches("0")) {
                    status = "request";
                } else if (status.matches("1")) {
                    status = "Approved";
                } else if (status.matches("2")) {
                    status = "rejected";
                }
                String Isi6 = status;
                String Isi7 = String.valueOf(o.getTsFile());

                String kolom[] = {Number, Isi1, Isi2, Isi3, Isi4, Isi5, Isi6, Isi7};
                number++;
                data.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ckck" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashboardEmp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCheckIn = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtNIK1 = new javax.swing.JTextField();
        txtName1 = new javax.swing.JTextField();
        txtEmail1 = new javax.swing.JTextField();
        txtPhone1 = new javax.swing.JTextField();
        txtDate1 = new javax.swing.JTextField();
        txtJob1 = new javax.swing.JTextField();
        txtStatus1 = new javax.swing.JTextField();
        txtManager1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ProfilEmp = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtNIK = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        OTreq = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOvertime = new javax.swing.JTable();
        btnBrows = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        txtDir = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        dt1 = new org.jdesktop.swingx.JXDatePicker();
        dt2 = new org.jdesktop.swingx.JXDatePicker();
        btnSearch = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        DasboardEmp = new javax.swing.JMenu();
        profileEmp = new javax.swing.JMenu();
        OTReq = new javax.swing.JMenu();
        LogoutEmp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("NIK                         :");

        jLabel2.setText("Name                      :");

        jLabel3.setText("Email                       :");

        jLabel4.setText("Phone Number     :");

        jLabel5.setText("Hire date                : ");

        jLabel6.setText("Job Title                 : ");

        jLabel7.setText("Status                    :");

        jLabel8.setText("Manager                : ");

        btnCheckIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCheckIn.setText("Check In");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        txtNIK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIK1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Employees Dashbord");

        javax.swing.GroupLayout DashboardEmpLayout = new javax.swing.GroupLayout(DashboardEmp);
        DashboardEmp.setLayout(DashboardEmpLayout);
        DashboardEmpLayout.setHorizontalGroup(
            DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardEmpLayout.createSequentialGroup()
                .addGroup(DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashboardEmpLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel11))
                    .addGroup(DashboardEmpLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNIK1)
                                .addComponent(txtName1)
                                .addComponent(txtPhone1)
                                .addComponent(txtDate1)
                                .addComponent(txtJob1)
                                .addComponent(txtStatus1)
                                .addComponent(txtManager1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        DashboardEmpLayout.setVerticalGroup(
            DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardEmpLayout.createSequentialGroup()
                .addGroup(DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addGroup(DashboardEmpLayout.createSequentialGroup()
                        .addGroup(DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DashboardEmpLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DashboardEmpLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DashboardEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(DashboardEmpLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel1)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel2)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel3)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel4)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel5)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel6)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel7)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardEmpLayout.createSequentialGroup()
                                        .addComponent(txtNIK1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtJob1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtManager1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("NIK                         :");

        txtNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIKActionPerformed(evt);
            }
        });

        jLabel18.setText("Name                      :");

        jLabel19.setText("Email                       :");

        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });

        jLabel20.setText("Phone Number       :");

        jLabel25.setText("Password               :");

        jPasswordField1.setText("jPasswordField1");

        jLabel9.setText("Change password");

        jToggleButton1.setText("Edit Profile");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Edit Profile");

        javax.swing.GroupLayout ProfilEmpLayout = new javax.swing.GroupLayout(ProfilEmp);
        ProfilEmp.setLayout(ProfilEmpLayout);
        ProfilEmpLayout.setHorizontalGroup(
            ProfilEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilEmpLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(ProfilEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProfilEmpLayout.createSequentialGroup()
                        .addGroup(ProfilEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ProfilEmpLayout.createSequentialGroup()
                                .addGroup(ProfilEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(ProfilEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNIK)
                            .addComponent(txtName)
                            .addComponent(txtEmail)
                            .addComponent(txtPhone)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ProfilEmpLayout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addGroup(ProfilEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jToggleButton1)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(497, 497, 497))
            .addGroup(ProfilEmpLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProfilEmpLayout.setVerticalGroup(
            ProfilEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(49, 49, 49)
                .addGroup(ProfilEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfilEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfilEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfilEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ProfilEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1)
                .addGap(118, 118, 118))
        );

        tblOvertime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOvertime);

        btnBrows.setText("Browse");
        btnBrows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBrowsMouseClicked(evt);
            }
        });

        jTextField1.setText("Search by Date");

        txtDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirActionPerformed(evt);
            }
        });

        jButton1.setText("Upload");

        jLabel10.setText("Browse File ");

        btnSearch.setText("Search");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Overtime Request");

        javax.swing.GroupLayout OTreqLayout = new javax.swing.GroupLayout(OTreq);
        OTreq.setLayout(OTreqLayout);
        OTreqLayout.setHorizontalGroup(
            OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OTreqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OTreqLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OTreqLayout.createSequentialGroup()
                        .addGroup(OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OTreqLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(33, 33, 33)
                                .addGroup(OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(OTreqLayout.createSequentialGroup()
                                        .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBrows))))
                            .addGroup(OTreqLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dt1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dt2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch))
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        OTreqLayout.setVerticalGroup(
            OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OTreqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGroup(OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OTreqLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OTreqLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(OTreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrows)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        DasboardEmp.setText("Dashboard");
        DasboardEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DasboardEmpMouseClicked(evt);
            }
        });
        DasboardEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DasboardEmpActionPerformed(evt);
            }
        });
        jMenuBar1.add(DasboardEmp);

        profileEmp.setText("Profile");
        profileEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileEmpMouseClicked(evt);
            }
        });
        profileEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileEmpActionPerformed(evt);
            }
        });
        jMenuBar1.add(profileEmp);

        OTReq.setText("Overtime");
        OTReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OTReqMouseClicked(evt);
            }
        });
        jMenuBar1.add(OTReq);

        LogoutEmp.setText("Log out");
        LogoutEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutEmpMouseClicked(evt);
            }
        });
        jMenuBar1.add(LogoutEmp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1074, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DashboardEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ProfilEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(OTreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(DashboardEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 68, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(ProfilEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 72, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(OTreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DasboardEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DasboardEmpActionPerformed

    }//GEN-LAST:event_DasboardEmpActionPerformed

    private void profileEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileEmpActionPerformed

    }//GEN-LAST:event_profileEmpActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        String NIK = Datas.getNik();
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        String dates = String.valueOf(timestamp);
        String hasil = "";
        String b = dates.substring(0, 10);
        String[] c = b.split("-");
        for (int i = 0; i < c.length; i++) {
            hasil = c[1] + "/" + c[2] + "/" + c[0];
        }
        String time = String.valueOf(timestamp);
        String times = time.substring(11, 19);
        int autiID = pci.getAlls().size() + 104;
        String ID = String.valueOf(autiID);
        System.out.println(ID);
        if (btnCheckIn.isSelected()) {

            System.out.println(ID + NIK + times + null + dates);
            if (pci.insert(ID, NIK, times, null, hasil)) {
                JOptionPane.showMessageDialog(null, "Check In succes");
            } else {
                JOptionPane.showMessageDialog(null, "Check In Failled!");
            }
            btnCheckIn.setText("Check Out");
        } else {

            int Id = autiID - 1;
            String IDnew = String.valueOf(Id);
            Presence pi = pci.getById(IDnew);
            String cekin = pi.getCheckIn();
            System.out.println(IDnew);
            if (pci.update(IDnew, NIK, cekin, times, hasil)) {
                JOptionPane.showMessageDialog(null, "Check Out succes");
            } else {
                JOptionPane.showMessageDialog(null, "Check Out Failled!");
            }
            btnCheckIn.setText("Check In");
            btnCheckIn.setEnabled(false);
        }
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void DasboardEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DasboardEmpMouseClicked
        DashboardEmp.setVisible(true);
        ProfilEmp.setVisible(false);
        OTreq.setVisible(false);
    }//GEN-LAST:event_DasboardEmpMouseClicked

    private void profileEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileEmpMouseClicked
        DashboardEmp.setVisible(false);
        ProfilEmp.setVisible(true);
        OTreq.setVisible(false);
    }//GEN-LAST:event_profileEmpMouseClicked

    private void txtNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIKActionPerformed

    private void OTReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OTReqMouseClicked
        DashboardEmp.setVisible(false);
        ProfilEmp.setVisible(false);
        OTreq.setVisible(true);

    }//GEN-LAST:event_OTReqMouseClicked

    private void txtNIK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIK1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIK1ActionPerformed

    private void LogoutEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutEmpMouseClicked
        int dialogButton = 0;
        int dialog = JOptionPane.showConfirmDialog(null, "Apakah anda ingin Logout ?", "Warning", dialogButton);
        if (dialog == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            LoginForm loginForm = new LoginForm();
            loginForm.show();
        } else {
        }
    }//GEN-LAST:event_LogoutEmpMouseClicked

    private void btnBrowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowsMouseClicked
//        FileChooser jfc = new FileChooser();
//       
//       jfc.showOpenDialog(null);
//
//        File file = jfc.getInitialDirectory();
//        String dir = file.getAbsolutePath();
//
//        txtDir.setText(dir);

        if (jfc == null) {
            jfc = new JFileChooser();
            jfc.addChoosableFileFilter(new mycustomFilter());
            jfc.setAcceptAllFileFilterUsed(false);
            
        }
        
        int returnfVal = jfc.showOpenDialog(mainFormEmployee.this);
        if (returnfVal == JFileChooser.APPROVE_OPTION) {
            File file = jfc.getSelectedFile();
            String dir = file.getAbsolutePath();
            txtDir.setText(dir);
        }
    }//GEN-LAST:event_btnBrowsMouseClicked

    private void txtDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        
    }//GEN-LAST:event_btnSearchMouseClicked

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyTyped
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_BACK_SPACE)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
        if (txtPhone.getText().length() >= 13) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPhoneKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFormEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFormEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFormEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFormEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFormEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DasboardEmp;
    private javax.swing.JPanel DashboardEmp;
    private javax.swing.JMenu LogoutEmp;
    private javax.swing.JMenu OTReq;
    private javax.swing.JPanel OTreq;
    private javax.swing.JPanel ProfilEmp;
    private javax.swing.JButton btnBrows;
    private javax.swing.JToggleButton btnCheckIn;
    private javax.swing.JButton btnSearch;
    private org.jdesktop.swingx.JXDatePicker dt1;
    private org.jdesktop.swingx.JXDatePicker dt2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JMenu profileEmp;
    private javax.swing.JTable tblOvertime;
    private javax.swing.JTextField txtDate1;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtJob1;
    private javax.swing.JTextField txtManager1;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtNIK1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtStatus1;
    // End of variables declaration//GEN-END:variables
}
