/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Email.sendEmail;
import controllers.OvertimeController;
import controllers.OvertimeControllerInterface;
import entities.Overtime;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.hibernate.Hibernate;
import org.hibernate.SessionFactory;
import tools.HibernateUtil;

/**
 *
 * @author Mukhlish
 */
public class mainFormManager extends javax.swing.JFrame {
    SessionFactory factory = HibernateUtil.getSessionFactory();
    OvertimeControllerInterface oci = new OvertimeController(factory);

    /**
     * Creates new form mainFormManager
     */
    public mainFormManager() {
        initComponents();
        DashboardManager.setVisible(true);
        OTRequest.setVisible(false);
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        
        BindingOvertime(oci.search(txtSearch.getText()));
        
        txtNIK.setEditable(false);
        txtName.setEditable(false);
        txtFee.setEditable(false);
        txtDuration.setEditable(false);
    }

    public void BindingOvertime(List<Object> overtimes) {
        Object[] header = {"No", "Overtime_Id", "Name", "NIK", "Duration", "Fee", "Status", "Timesheet"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        tblOvertime.setModel(data);
        int number = 1;

        try {
            for (Object overtime : overtimes) {
                Overtime o = (Overtime) overtime;
                String Number = String.valueOf(number);
                String Isi1 = String.valueOf(o.getOvertimeId());
                String Isi2 = String.valueOf(o.getNik().getName());
                String Isi3 = String.valueOf(o.getNik().getNik());
                String Isi4 = String.valueOf(o.getOtDuration());
                String Isi5 = String.valueOf(o.getFee());
                String status = String.valueOf(o.getStatus());
                if (status.matches("0")) {
                    status = "request";
                } else if (status.matches("1")) {
                    status = "Approved";
                } else if (status.matches("2")) {
                    status = "rejected";
                }
                String Isi6 = status;
                String Isi7 = String.valueOf(o.getTsFile());

                String kolom[] = {Number, Isi1, Isi2, Isi3, Isi4, Isi5, Isi6, Isi7};
                number++;
                data.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ckck" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DashboardManager = new javax.swing.JPanel();
        OTRequest = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOvertime = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNIK = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtDuration = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbApprove = new javax.swing.JComboBox<>();
        btnSaveApprove = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFee = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        managerDash = new javax.swing.JMenu();
        reqOT = new javax.swing.JMenu();
        LogOutManager = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout DashboardManagerLayout = new javax.swing.GroupLayout(DashboardManager);
        DashboardManager.setLayout(DashboardManagerLayout);
        DashboardManagerLayout.setHorizontalGroup(
            DashboardManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
        );
        DashboardManagerLayout.setVerticalGroup(
            DashboardManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jPanel1.add(DashboardManager, "card2");

        tblOvertime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOvertime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOvertimeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOvertime);

        jLabel1.setText("NIK");

        jLabel2.setText("Name");

        jLabel3.setText("Duration");

        jLabel4.setText("Status");

        cmbApprove.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Approve", "Reject" }));

        btnSaveApprove.setText("Save");
        btnSaveApprove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveApproveMouseClicked(evt);
            }
        });

        jLabel5.setText("view Report");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setText("Fee");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout OTRequestLayout = new javax.swing.GroupLayout(OTRequest);
        OTRequest.setLayout(OTRequestLayout);
        OTRequestLayout.setHorizontalGroup(
            OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OTRequestLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(OTRequestLayout.createSequentialGroup()
                        .addGroup(OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(46, 46, 46)
                        .addGroup(OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addComponent(txtNIK)))
                    .addGroup(OTRequestLayout.createSequentialGroup()
                        .addGroup(OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(32, 32, 32)
                        .addGroup(OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDuration)
                            .addGroup(OTRequestLayout.createSequentialGroup()
                                .addComponent(cmbApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnSaveApprove)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtFee))))
                .addGap(18, 18, 18)
                .addGroup(OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(OTRequestLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OTRequestLayout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        OTRequestLayout.setVerticalGroup(
            OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OTRequestLayout.createSequentialGroup()
                .addGroup(OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OTRequestLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OTRequestLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGroup(OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OTRequestLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(OTRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbApprove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveApprove)))
                    .addGroup(OTRequestLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(OTRequest, "card3");

        managerDash.setText("Dashboard");
        managerDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managerDashMouseClicked(evt);
            }
        });
        jMenuBar1.add(managerDash);

        reqOT.setText("Overtime Req");
        reqOT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reqOTMouseClicked(evt);
            }
        });
        jMenuBar1.add(reqOT);

        LogOutManager.setText("Log Out");
        LogOutManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutManagerMouseClicked(evt);
            }
        });
        jMenuBar1.add(LogOutManager);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managerDashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerDashMouseClicked
        DashboardManager.setVisible(true);
        OTRequest.setVisible(false);
        BindingOvertime(oci.search(txtSearch.getText()));
    }//GEN-LAST:event_managerDashMouseClicked

    private void reqOTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reqOTMouseClicked
        DashboardManager.setVisible(false);
        OTRequest.setVisible(true);
        BindingOvertime(oci.search(txtSearch.getText()));
    }//GEN-LAST:event_reqOTMouseClicked

    private void LogOutManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutManagerMouseClicked
        int dialogButton = 0;
        int dialog = JOptionPane.showConfirmDialog(null, "Apakah anda ingin Logout ?", "Warning", dialogButton);
        if (dialog == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            LoginForm loginForm = new LoginForm();
            loginForm.show();
        } else {
        }
    }//GEN-LAST:event_LogOutManagerMouseClicked

    private void btnSaveApproveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveApproveMouseClicked
        String approve = (String) cmbApprove.getSelectedItem();
        if (approve.matches("Approve")) {
            approve = "1";
            sendEmail email = new sendEmail();
            email.sent(true);
        } else if (approve.matches("Reject")) {
            approve = "2";
            sendEmail email = new sendEmail();
            email.sent(false);
        }

        int i = tblOvertime.getSelectedRow();
        TableModel model = tblOvertime.getModel();
        String OVERTIME_ID = model.getValueAt(i, 1).toString();
        Object el = oci.getById(OVERTIME_ID);
        Overtime o = (Overtime) el;
        String NIK = txtNIK.getText();
        String PRESENCE_ID = String.valueOf(o.getPresenceId().getPresenceId());
        String OT_DURATION = txtDuration.getText();
        String FEE = txtFee.getText();
        String STATUS = String.valueOf(o.getStatus());
        String TS_FILE = String.valueOf(o.getTsFile());
        //     System.out.println(OVERTIME_ID + OT_DURATION + FEE + approve + TS_FILE + NIK + PRESENCE_ID);
        if (oci.update(OVERTIME_ID, NIK, PRESENCE_ID, OT_DURATION, FEE, approve, TS_FILE)) {
            JOptionPane.showMessageDialog(null, "updated");
            BindingOvertime(oci.search(txtSearch.getText()));
//            sendEmail email = new sendEmail();
//            email.sent(true);
        } else {
            JOptionPane.showMessageDialog(null, "failed");
//            sendEmail email = new sendEmail();
//            email.sent(false);
        }
    }//GEN-LAST:event_btnSaveApproveMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        String filename = "E:\\KERJA\\Project\\TugasOvertime-master\\src\\report\\overtime.jasper";
        String filetofill = "E:\\KERJA\\Project\\TugasOvertime-master\\src\\report\\overtime.jrxml";
        reportForm form = new reportForm(filename, filetofill);
        form.show();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void tblOvertimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOvertimeMouseClicked
        int i = tblOvertime.getSelectedRow();
        TableModel model = tblOvertime.getModel();
        txtName.setText(model.getValueAt(i, 3).toString());
        txtNIK.setText(model.getValueAt(i, 3).toString());
        Overtime overtime = (Overtime) oci.getById((String) model.getValueAt(i, 1));
        String present = String.valueOf(overtime.getPresenceId().getPresenceId());
        txtDuration.setText(model.getValueAt(i, 4).toString());
        txtFee.setText(model.getValueAt(i, 5).toString());

        String status = model.getValueAt(i, 6).toString();
        System.out.println(status);
        if (status.matches("request")) {
            cmbApprove.setEnabled(true);
            btnSaveApprove.setEnabled(true);
        } else if (status.matches("Approved")) {
            cmbApprove.setEnabled(false);
            btnSaveApprove.setEnabled(false);
        } else if (status.matches("rejected")) {
            cmbApprove.setEnabled(false);
            btnSaveApprove.setEnabled(false);
        }
    }//GEN-LAST:event_tblOvertimeMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        BindingOvertime(oci.search(txtSearch.getText()));
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFormManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFormManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFormManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFormManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFormManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DashboardManager;
    private javax.swing.JMenu LogOutManager;
    private javax.swing.JPanel OTRequest;
    private javax.swing.JButton btnSaveApprove;
    private javax.swing.JComboBox<String> cmbApprove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu managerDash;
    private javax.swing.JMenu reqOT;
    private javax.swing.JTable tblOvertime;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtFee;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
